var DATA = [
      { id:0, label:"com.datalogic.extension.selfshopping", link:"reference/com/datalogic/extension/selfshopping/package-summary.html", type:"package", deprecated:"false" },
      { id:1, label:"com.datalogic.extension.selfshopping.Version", link:"reference/com/datalogic/extension/selfshopping/Version.html", type:"class", deprecated:"false" },
      { id:2, label:"com.datalogic.extension.selfshopping.cradle", link:"reference/com/datalogic/extension/selfshopping/cradle/package-summary.html", type:"package", deprecated:"false" },
      { id:3, label:"com.datalogic.extension.selfshopping.cradle.Cradle", link:"reference/com/datalogic/extension/selfshopping/cradle/Cradle.html", type:"class", deprecated:"false" },
      { id:4, label:"com.datalogic.extension.selfshopping.cradle.CradleInsertionListener", link:"reference/com/datalogic/extension/selfshopping/cradle/CradleInsertionListener.html", type:"class", deprecated:"false" },
      { id:5, label:"com.datalogic.extension.selfshopping.cradle.CradleManager", link:"reference/com/datalogic/extension/selfshopping/cradle/CradleManager.html", type:"class", deprecated:"false" },
      { id:6, label:"com.datalogic.extension.selfshopping.cradle.CradleType", link:"reference/com/datalogic/extension/selfshopping/cradle/CradleType.html", type:"class", deprecated:"false" },
      { id:7, label:"com.datalogic.extension.selfshopping.cradle.joyatouch", link:"reference/com/datalogic/extension/selfshopping/cradle/joyatouch/package-summary.html", type:"package", deprecated:"false" },
      { id:8, label:"com.datalogic.extension.selfshopping.cradle.joyatouch.ConfigArea", link:"reference/com/datalogic/extension/selfshopping/cradle/joyatouch/ConfigArea.html", type:"class", deprecated:"false" },
      { id:9, label:"com.datalogic.extension.selfshopping.cradle.joyatouch.CradleJoyaTouch", link:"reference/com/datalogic/extension/selfshopping/cradle/joyatouch/CradleJoyaTouch.html", type:"class", deprecated:"false" },
      { id:10, label:"com.datalogic.extension.selfshopping.cradle.joyatouch.CustomArea", link:"reference/com/datalogic/extension/selfshopping/cradle/joyatouch/CustomArea.html", type:"class", deprecated:"false" },
      { id:11, label:"com.datalogic.extension.selfshopping.cradle.joyatouch.GenericArea", link:"reference/com/datalogic/extension/selfshopping/cradle/joyatouch/GenericArea.html", type:"class", deprecated:"false" },
      { id:12, label:"com.datalogic.extension.selfshopping.cradle.joyatouch.LedAction", link:"reference/com/datalogic/extension/selfshopping/cradle/joyatouch/LedAction.html", type:"class", deprecated:"false" },
      { id:13, label:"com.datalogic.extension.selfshopping.cradle.joyatouch.LockAction", link:"reference/com/datalogic/extension/selfshopping/cradle/joyatouch/LockAction.html", type:"class", deprecated:"false" },
      { id:14, label:"com.datalogic.extension.selfshopping.cradle.joyatouch.StateInfo", link:"reference/com/datalogic/extension/selfshopping/cradle/joyatouch/StateInfo.html", type:"class", deprecated:"false" },
      { id:15, label:"com.datalogic.extension.selfshopping.led", link:"reference/com/datalogic/extension/selfshopping/led/package-summary.html", type:"package", deprecated:"false" },
      { id:16, label:"com.datalogic.extension.selfshopping.led.DimmingLed", link:"reference/com/datalogic/extension/selfshopping/led/DimmingLed.html", type:"class", deprecated:"false" },
      { id:17, label:"com.datalogic.extension.selfshopping.led.DimmingSequence", link:"reference/com/datalogic/extension/selfshopping/led/DimmingSequence.html", type:"class", deprecated:"false" },
      { id:18, label:"com.datalogic.extension.selfshopping.led.DimmingSequencePoint", link:"reference/com/datalogic/extension/selfshopping/led/DimmingSequencePoint.html", type:"class", deprecated:"false" },
      { id:19, label:"com.datalogic.extension.selfshopping.led.Led", link:"reference/com/datalogic/extension/selfshopping/led/Led.html", type:"class", deprecated:"false" },
      { id:20, label:"com.datalogic.extension.selfshopping.led.SelfshoppingLedManager", link:"reference/com/datalogic/extension/selfshopping/led/SelfshoppingLedManager.html", type:"class", deprecated:"false" },
      { id:21, label:"com.datalogic.extension.selfshopping.led.action", link:"reference/com/datalogic/extension/selfshopping/led/action/package-summary.html", type:"package", deprecated:"false" },
      { id:22, label:"com.datalogic.extension.selfshopping.led.action.LedAction", link:"reference/com/datalogic/extension/selfshopping/led/action/LedAction.html", type:"class", deprecated:"false" },
      { id:23, label:"com.datalogic.extension.selfshopping.led.action.LedActionBlink", link:"reference/com/datalogic/extension/selfshopping/led/action/LedActionBlink.html", type:"class", deprecated:"false" },
      { id:24, label:"com.datalogic.extension.selfshopping.led.action.LedActionDim", link:"reference/com/datalogic/extension/selfshopping/led/action/LedActionDim.html", type:"class", deprecated:"false" },
      { id:25, label:"com.datalogic.extension.selfshopping.led.action.LedActionSetBrightness", link:"reference/com/datalogic/extension/selfshopping/led/action/LedActionSetBrightness.html", type:"class", deprecated:"false" },
      { id:26, label:"com.datalogic.extension.selfshopping.led.action.LedActionTurnOff", link:"reference/com/datalogic/extension/selfshopping/led/action/LedActionTurnOff.html", type:"class", deprecated:"false" },
      { id:27, label:"com.datalogic.extension.selfshopping.led.action.LedActionTurnOn", link:"reference/com/datalogic/extension/selfshopping/led/action/LedActionTurnOn.html", type:"class", deprecated:"false" },
      { id:28, label:"com.datalogic.extension.selfshopping.led.action.persistence", link:"reference/com/datalogic/extension/selfshopping/led/action/persistence/package-summary.html", type:"package", deprecated:"false" },
      { id:29, label:"com.datalogic.extension.selfshopping.led.action.persistence.PersistJSON", link:"reference/com/datalogic/extension/selfshopping/led/action/persistence/PersistJSON.html", type:"class", deprecated:"false" },
      { id:30, label:"com.datalogic.extension.selfshopping.led.event", link:"reference/com/datalogic/extension/selfshopping/led/event/package-summary.html", type:"package", deprecated:"false" },
      { id:31, label:"com.datalogic.extension.selfshopping.led.event.LedEvent", link:"reference/com/datalogic/extension/selfshopping/led/event/LedEvent.html", type:"class", deprecated:"false" }

    ];
